### ISSUE TITLE
README.md error

### ISSUE THREAD

**Issue by J-Siu** [gyorb/hugo-dusk#26]
In README.md:

The following lines should be above `[author]`, else they become part of it.

```toml
SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true
```
